# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  name: Fortify
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'java -jar "C:\fortifytask\fortify-api-client-latest.jar" create -n Cdxha.exceptions1-java -v Main'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
     /opt/sca/scancentral -sscurl $(var.sscurl) -ssctoken $(var.ssctoken) start -bt none -upload --application Cdxha.exceptions1-java --application-version $(Build.SourceBranchName) -uptoken $(var.uptoken) 
      
      